name: Fetch and Post StackOverflow Questions

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  fetch_and_post_questions:
    runs-on: ubuntu-latest
    env:
      STACK_OVERFLOW_TAG: jaeger
      TIMESTAMP_FILE: ./so2slack_timestamp.txt

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Fetch and post questions
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        python ./.github/scripts/so2slack.py
    - name: Commit and push state file
      run: |
        git config user.name "GitHub Action"
        git config user.email "noreply@example.com"
        git add "${TIMESTAMP_FILE}"
        git commit -m "Update timestamp"
        git push
