# adopted from https://github.com/open-telemetry/community/pull/1450
name: Fetch and Post StackOverflow Questions

on:
  schedule:
    # Runs at 08:00, only on Monday.
    - cron: '0 8 * * 1'

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fetch_and_post_questions:
    runs-on: ubuntu-latest
    env:
      STACK_OVERFLOW_TAG: jaeger
      TIMESTAMP_FILE: ./so2slack_timestamp.txt

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch and post questions
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        python ./.github/scripts/so2slack.py

    - name: Check if state.txt was updated
      id: check_state
      run: |
        echo "updated=0" > $GITHUB_OUTPUT
        git diff --quiet --exit-code -- "${TIMESTAMP_FILE}" || echo "updated=1" > $GITHUB_OUTPUT

    - name: Commit and push state file
      if: steps.check_state.outputs.updated == '1'
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add "${TIMESTAMP_FILE}"
        git commit -m "Update timestamp $(date -r $(cat so2slack_timestamp.txt))"
        git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
        git push
