# adopted from https://github.com/open-telemetry/community/pull/1450
name: Fetch and Post StackOverflow Questions

on:
  schedule:
    # Runs at 08:00, only on Monday.
    - cron: '0 8 * * 1'

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fetch_and_post_questions:
    runs-on: ubuntu-latest
    env:
      STACK_OVERFLOW_TAG: jaeger
      TIMESTAMP_FILE: ./so2slack_timestamp.txt

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Fetch and post questions
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo python ./.github/scripts/so2slack.py
        date > "${TIMESTAMP_FILE}"
    - name: Commit and push state file
      run: |
        git config user.name 'jaegertracingbot'
        git config user.email 'jaegertracingbot@users.noreply.github.com'
        git add "${TIMESTAMP_FILE}"
        git commit -m "Update timestamp"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
